from enum import Enum

class DirectDebitEnum(Enum):
    DIRECT_DEBIT_ALLO_SNAP = "DIRECT_DEBIT_ALLO_SNAP"
    DIRECT_DEBIT_CIMB_SNAP = "DIRECT_DEBIT_CIMB_SNAP"
    DIRECT_DEBIT_MANDIRI_SNAP = "DIRECT_DEBIT_MANDIRI_SNAP"
    DIRECT_DEBIT_BRI_SNAP = "DIRECT_DEBIT_BRI_SNAP"
    EMONEY_OVO_SNAP = "EMONEY_OVO_SNAP"
    EMONEY_SHOPEE_PAY_SNAP = "EMONEY_SHOPEE_PAY_SNAP"
    EMONEY_DANA_SNAP = "EMONEY_DANA_SNAP"

